#!/bin/bash
awk '
    ($1=="HETATM" && ($12=="N" || $12=="O") ) || \
    ($1=="HETATM" && ($12=="H") ) {
        atom[$2] = 1
        x[$2] = $7
        y[$2] = $8
        z[$2] = $9
	name[$2] = $12
    }
    END {
        for (a in atom) {
            for (b in atom) {
                if (a > b ) {
                    dist = sqrt((x[a]-x[b])^2 + (y[a]-y[b])^2 + (z[a]-z[b])^2)
                    if (dist < 1.3)
                        printf "%s.*%s.*%s.*%s %.4f\n%s.*%s.*%s.*%s\n", x[a], y[a], z[a], name[a], dist, x[b], y[b], z[b], name[b]
                }
            }
        }
    }
' $1
