#!/bin/bash

 here=`pwd`
 cd $here

 thing=`echo */`
 if [[ "$thing" == '*/' ]]; then
  exit 0
 else
  list=`find . -type d -iname  KraftWerk`
 fi

 for i in $list
 do
   cd $i
   tarKraftWerk &
   rm *.err *.log
   cd ../
   pwd
   tar -czf KraftWerk.tgz KraftWerk/
   rm -rf KraftWerk
   cd $here
 done
