#!/bin/bash
#$1 is the pdb file to check
#$2 is the metal of interest

METAL=$2
awk '
    ($1== "ATOM" && ($NF=="N" || $NF=="O" || $NF=="S" || $NF=="SE" || $NF=="Se") ) || \
    ($1== "HETATM" && ($3=="'$METAL'") ) {
        atom[$2] = 1
        x[$2] = $(NF-5)
        y[$2] = $(NF-4)
        z[$2] = $(NF-3)
	name[$2] = $NF
	pdbatom[$2] = $3
	pdbgroup[$2] = $4
	resnum[$2] = $(NF-6)
	res[$2] = $(NF-8)
    }
    END {
        for (a in atom) {
            for (b in atom) {
                if (a > b ) {
                    dist = sqrt((x[a]-x[b])^2 + (y[a]-y[b])^2 + (z[a]-z[b])^2)
                    if (dist < 2.6 && ( pdbatom[a]=="'$METAL'" || pdbatom[b]=="'$METAL'") )
                        printf "%s %s %s%s\n", pdbgroup[b], pdbatom[a], res[a], resnum[a]
                }
            }
        }
    }
' $1
